# Generated by Django 3.2.7 on 2021-10-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_migracion_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platomodel',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at'),
        ),
    ]
